import type { Category } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'walking',
    name: 'Yürüyüş',
    icon: '🦶',
    color: '#22c55e',
    description: 'Günlük yürüyüş ve adım hedefleri',
  },
  {
    id: 'cardio',
    name: 'Kardiyo',
    icon: '🏃',
    color: '#f97316',
    description: 'Koşu, bisiklet ve kardiyo egzersizleri',
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: '💪',
    color: '#ef4444',
    description: 'Ağırlık antrenmanı ve vücut geliştirme',
  },
  {
    id: 'yoga',
    name: 'Yoga',
    icon: '🧘',
    color: '#a855f7',
    description: 'Yoga ve esneme hareketleri',
  },
  {
    id: 'cycling',
    name: 'Bisiklet',
    icon: '🚴',
    color: '#06b6d4',
    description: 'Bisiklet sürme ve spinning',
  },
  {
    id: 'swimming',
    name: 'Yüzme',
    icon: '🏊',
    color: '#0ea5e9',
    description: 'Yüzme ve su sporları',
  },
  {
    id: 'sports',
    name: 'Takım Sporları',
    icon: '⚽',
    color: '#dc2626',
    description: 'Futbol, basketbol ve diğer takım sporları',
  },
  {
    id: 'nutrition',
    name: 'Beslenme',
    icon: '🥗',
    color: '#84cc16',
    description: 'Sağlıklı beslenme ve diyet takibi',
  },
  {
    id: 'sleep',
    name: 'Uyku',
    icon: '🌙',
    color: '#6366f1',
    description: 'Düzenli uyku alışkanlığı',
  },
  {
    id: 'meditation',
    name: 'Meditasyon',
    icon: '🌸',
    color: '#e879f9',
    description: 'Meditasyon, nefes ve zihin egzersizleri',
  },
  {
    id: 'reading',
    name: 'Kitap Okuma',
    icon: '📚',
    color: '#eab308',
    description: 'Günlük kitap okuma alışkanlığı',
  },
  {
    id: 'language',
    name: 'Dil Öğrenme',
    icon: '🌍',
    color: '#3b82f6',
    description: 'Yabancı dil öğrenme ve pratik',
  },
  {
    id: 'education',
    name: 'Online Eğitim',
    icon: '💻',
    color: '#8b5cf6',
    description: 'Online kurslar ve dijital öğrenme',
  },
  {
    id: 'writing',
    name: 'Yazarlık',
    icon: '✍️',
    color: '#f59e0b',
    description: 'Günlük, blog veya yaratıcı yazarlık',
  },
  {
    id: 'coding',
    name: 'Kodlama',
    icon: '👨‍💻',
    color: '#10b981',
    description: 'Programlama ve yazılım geliştirme',
  },
  {
    id: 'music',
    name: 'Müzik',
    icon: '🎸',
    color: '#ec4899',
    description: 'Enstrüman çalma ve müzik pratiği',
  },
  {
    id: 'art',
    name: 'Sanat & Çizim',
    icon: '🎨',
    color: '#f43f5e',
    description: 'Resim, çizim ve yaratıcı sanatlar',
  },
  {
    id: 'photography',
    name: 'Fotoğrafçılık',
    icon: '📷',
    color: '#64748b',
    description: 'Fotoğraf çekme ve görsel sanatlar',
  },
  {
    id: 'gaming',
    name: 'Oyun',
    icon: '🎮',
    color: '#7c3aed',
    description: 'Video oyunları ve e-spor',
  },
  {
    id: 'cooking',
    name: 'Yemek Pişirme',
    icon: '🍳',
    color: '#fb923c',
    description: 'Yemek tarifi deneme ve mutfak sanatı',
  },
  {
    id: 'finance',
    name: 'Finans',
    icon: '💰',
    color: '#16a34a',
    description: 'Bütçe yönetimi ve finansal hedefler',
  },
  {
    id: 'work',
    name: 'Kariyer',
    icon: '⚡',
    color: '#475569',
    description: 'İş hedefleri ve kariyer gelişimi',
  },
  {
    id: 'social',
    name: 'Sosyalleşme',
    icon: '🤝',
    color: '#f472b6',
    description: 'Sosyal aktiviteler ve ilişkiler',
  },
  {
    id: 'travel',
    name: 'Seyahat',
    icon: '✈️',
    color: '#0284c7',
    description: 'Seyahat planları ve keşifler',
  },
  {
    id: 'outdoor',
    name: 'Doğa & Kamp',
    icon: '🏔️',
    color: '#15803d',
    description: 'Doğa yürüyüşü, kamp ve açık hava',
  },
  {
    id: 'wellness',
    name: 'Wellness',
    icon: '🌿',
    color: '#059669',
    description: 'Genel sağlık ve yaşam kalitesi',
  },
];

export const getCategoryById = (id: string) =>
  CATEGORIES.find((c) => c.id === id);
